# version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - sonar-db
    networks:
      - sonarqube

  sonar-db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonarqube

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar_scanner
    environment:
      SONAR_HOST_URL: http://localhost:9000
      SONAR_LOGIN: sqp_29fa0f9f75930756394ffcb88fc481036c6f6f4d # Replace with the token you generate from the SonarQube UI
    volumes:
      - /home/irwinrex/Documents/equipo/v2_pt360_api:/usr/src
    depends_on:
      - sonarqube
    command: >
      -Dsonar.projectKey=test \
      -Dsonar.sources=. \
      -Dsonar.host.url=http://localhost:9000 \
      -Dsonar.token=sqp_29fa0f9f75930756394ffcb88fc481036c6f6f4d
    networks:
      - sonarqube
  
networks:
  sonarqube:
    driver: bridge

